OBJS-$(CONFIG_BWDIF_FILTER)                  += aarch64/vf_bwdif_init_aarch64.o
OBJS-$(CONFIG_COLORDETECT_FILTER)            += aarch64/vf_colordetect_init.o
OBJS-$(CONFIG_NLMEANS_FILTER)                += aarch64/vf_nlmeans_init.o
OBJS-$(CONFIG_NOISE_FILTER)                  += aarch64/vf_noise_init_aarch64.o
OBJS-$(CONFIG_OVERLAY_FILTER)                += aarch64/vf_overlay_init_aarch64.o

NEON-OBJS-$(CONFIG_BWDIF_FILTER)             += aarch64/vf_bwdif_neon.o
NEON-OBJS-$(CONFIG_COLORDETECT_FILTER)       += aarch64/vf_colordetect_neon.o
NEON-OBJS-$(CONFIG_NLMEANS_FILTER)           += aarch64/vf_nlmeans_neon.o
NEON-OBJS-$(CONFIG_NOISE_FILTER)             += aarch64/vf_noise_neon.o
NEON-OBJS-$(CONFIG_OVERLAY_FILTER)           += aarch64/vf_overlay_neon.o
